In [5]:
import pandas as pd

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    <code>read_csv</code> پارامترهای مهم تابع 
    </font>
</h2>

```python
pd.read_csv(file_path, sep=',', header='infer', squeeze=False, prefix=<no_default>, error_bad_lines=None, nrows=None)
```

<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=3>
        
| پارامتر| توضیحات|
| --------|------- |
| file_path| آدرس فایل یا URL فایلی که می‌خواهیم از آن داده را بخوانیم. آدرس‌دهی می‌تواند نسبی یا مطلق باشد.|
| sep| هر ستون را با این کاراکتر از ستون‌های دیگر جدا می‌کند. چون قرار است CSV بخوانیم، به طور پیش‌فرض مقدار `sep` کاراکتر ‍`,` است. اما ممکن است حتی فایل‌هایی که پسنود csv دارند با کاما از یکدیگر جدا نشده باشند!|
| header | این پارامتر شماره سطری را نشان می‌دهد که اسم ستون‌ها در آن آمده است. به طور پیش‌فرض روی حالت `infer` قرار دارد؛ یعنی اولین سطر را به عنوان اسم ستون لحاظ می‌کند. حالت `infer` معادل `header=0` است.<br>می‌تواند عدد صحیح، لیستی از اعداد صحیح یا `None` باشد.<br><br>- اگر یک عدد صحیح باشد، شماره سطری که اسامی ستون‌ها در آن‌جا قرار دارد را نشان می‌دهد.<br>- اگر لیستی از اعداد صحیح باشد، منجر به ایجاد دیتافریم‌هایی با چندین نمایه می‌شود که این مبحث خارج از مباحث این دوره است.<br>- اگر `None` باشد، هیچ اسمی برای ستون‌ها انتخاب نمی‌شود و پانداز به صورت پیش‌فرض ستون‌ها را از 0 تا C - 1 اسم‌گذاری می‌کند که C تعداد ستون‌هاست. |
| squeeze| اگر فایلی که می‌خوانیم یک ستون داشته باشد، می‌توانیم در قالب یک دیتاسری خروجی بگیریم. نوع مقادیر این پارامتر `bool‍` است. <br><br>در صورتی که فایل مورد نظر تنها دارای یک ستون باشد :<br>- اگر مقدار این پارامتر False باشد، خروجی `read_csv` دیتافریم است.<br>- اگر True باشد، خروجی `read_csv` دیتاسری است.|
|prefix| فرض کنید به طور پیش‌فرض اسم ستون‌های یک دیتافریم اعداد 0 تا C -1 هستند که C تعداد ستون‌هاست. اگر بخواهیم قبل از اعداد یک رشته اضافه کنیم به طوری‌که فرضا اسم ستون‌ها X0, X1, X2, … شود می‌توانیم رشته مورد نظر را در پارامتر prefix قرار دهیم. در حالتی که اسم ستون‌ها عدد نیستند هم می‌توانیم prefix داشته باشیم.|
| error_bad_lines | برخی سطر‌ها ممکن است معیوب باشند. به طور مثال اگر دیتافریم ۱۰ ستون دارد، سطری ۱۱ ستون داشته باشد (یک کاما اضافه‌تر داشته‌باشد). در حالت پیش‌فرض، پانداز برای خواندن این فایل‌ها دچار error می‌شود. اگر مقدار این پارامتر را برابر False قرار دهیم، پانداز سطرهای معیوب را از دیتافریمی که خروجی می‌دهد، حذف می‌کند. اگر مقدار این پارامتر را تنظیم نکنیم، عملیات با خطا روبرو شده و هیچ دیتافریمی خروجی نمی‌گیریم.|
|nrows| در شرایطی ممکن است نیاز باشد تنها تعدادی از سطر‌های یک فایل را بخوانیم؛ مثلا مواقعی که فایل حجیم باشد! <br>برای تعیین تعداد سطر‌هایی که می‌خواهیم از یک فایل بخوانیم از این پارامتر استفاده می‌کنیم. اگر مقدار 1000 داشته باشد، تنها 1000 سطر اول از فایل را دریافت می‌کنیم.|
</font>
</div>

In [2]:
df = pd.read_csv('./population.csv')
df

                                         Race  Population (2020) Percentage
0                            Total population            5706494       100%
1                  White or European American            4423146      77.5%
2                   Black or African American             398434       7.0%
3                             Native American              68641       1.2%
4                              Asian American             299190       5.2%
5  Native Hawaiian and Other Pacific Islander               2918       0.1%
6                             Some other race             168444       3.0%
7                           Two or more races             345721       6.1%

<br>
    
<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    <code>read_excel</code> پارامترهای مهم تابع 
    </font>
</h2>

```python
pd.read_excel(file_path, sheet_name=0, header=0, squeeze=False, nrows=None)
```

<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=3>
        
| پارامتر    | توضیحات|
|--------|----------- |
| file_path  | آدرس فایل یا URL فایلی که می‌خواهیم از آن داده را بخوانیم. آدرس‌دهی می‌تواند نسبی یا مطلق باشد.|
| sheet_name | در هر فایل excel می‌تواند چندین sheet وجود داشته باشد. با این پارامتر می‌توانیم تعیین کنیم می‌خواهیم کدام sheet از فایل اکسل را بخوانیم. این آرگومان می‌تواند یک عدد صحیح، یک رشته یا یک لیست را به خود بپذیرد. در لیست پایین آن‌ها را توضیح می‌دهیم.<br><br>- اگر عدد صحیح n باشد، به nامین sheet موجود در فایل اشاره می‌کند. بازه قابل قبول n از 0 تا اعداد بیشتر از 0 است. به‌عنوان مثال `sheet=0` یعنی اولین sheet موجود در فایل اکسل. به طور پیش‌فرض روی عدد 0 تنظیم شده است.<br>- اگر این آرگومان sheet 1  باشد، به sheetای اشاره می‌کند که اسمش sheet 1 است.<br>- اگر مقدار آرگومان فرضا برابر `[0,1,"sheet 1"]` باشد، اولین، دومین و sheetای به اسم sheet 1 را در قالب دیکشنری پایتون لود می‌کند. |
| header     | این آرگومان، شماره سطری را نشان می‌دهد که اسم ستون‌ها در آن آمده است. به طور پیش‌فرض روی حالت `infer` قرار دارد؛ یعنی اولین سطر را به عنوان اسم ستون لحاظ می‌کند. حالت `infer` معادل `header=0` است.<br>می‌تواند عدد صحیح، لیستی از اعداد صحیح یا `None` باشد.<br><br>- اگر یک عدد صحیح باشد، شماره سطری که اسامی ستون‌ها در آن‌جا قرار دارد را نشان می‌دهد.<br>- اگر لیستی از اعداد صحیح باشد، منجر به ایجاد دیتافریم‌هایی با چندین نمایه می‌شود که این مبحث خارج از مباحث این دوره است.<br>- اگر `None` باشد، هیچ اسمی برای ستون‌ها انتخاب نمی‌شود و پانداز به صورت پیش‌فرض ستون‌ها را از 0 تا C - 1 اسم‌گذاری می‌کند که C تعداد ستون‌هاست.                                                                     |
| squeeze    | اگر فایلی که می‌خوانیم یک ستون داشته باشد، می‌توانیم در قالب یک دیتاسری خروجی بگیریم. نوع مقادیر این آرگومان، `bool‍` است. در صورتی که فایل مورد نظر تنها دارای یک ستون باشد :<br><br>- اگر مقدار این آرگومان False باشد، خروجی `read_excel` دیتافریم است.<br>- اگر True باشد، خروجی `read_excel` دیتاسری است.|
|nrows| شرایطی ممکن است نیاز باشد تنها تعدادی از سطر‌های یک فایل را بخوانیم؛ مثلا مواقعی که فایل حجیم باشد! <br>برای تعیین تعداد سطر‌هایی که می‌خواهیم از یک فایل بخوانیم از این آرگومان استفاده می‌کنیم. اگر مقدار 1000 داشته باشد، تنها 1000 سطر اول از فایل را دریافت می‌کنیم.|


</div>

<br>
    
<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    <code>read_html</code> پارامترهای مهم تابع 
    </font>
</h2>

```python
pd.read_html(source, match='.+', flavor=None, header=None)
```

<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=3>
        
| پارامتر | توضیحات|
| ------- | --------|
| source  | منبعی از جنس HTML که قصد داریم جداول آن‌ را استخراج کنیم. منبع می‌تواند در قالب‌های زیر باشد.<br><br>- آدرس یک فایل HTML در حافظه محلی. مثلا `home/pandas/index.html‍` <br>- آدرس یک فایل HTML در فضای وب.<br>- یک رشته که درون آن کد HTML نوشته شده باشد. در مثال‌ این نمونه را بیشتر بررسی خواهیم کرد. |
| match   | ممکن است در یک فایل HTML جدول‌های زیادی وجود داشته باشد. برای اینکه بتوانیم راحت‌تر جدول مورد نظر خود را پیدا کنیم می‌توانیم یک رشته یا یک عبارت منظم (Regex) متناظر با جداول مد نظر خود را در این پارامتر قرار دهیم. در مثال‌ این قسمت بیشتر با کاربرد پارامتر `match` آشنا می‌شویم.                                                                                        |
| flavor  | برای تجزیه کردن (parse) HTML ورودی، موتورهای مختلفی وجود دارد. به طور پیش‌فرض pandas از lxml برای تجزیه HTML و تبدیلش به دیتافریم استفاده می‌کند. اگر استفاده از lxml دچار مشکل شود سراغ موتورهای `bs4` و `html5lib` می‌رود. اگر نتواند هیچ کدام از این موتورها را استفاده کند، اِرُر می‌دهد و در متن اِرُر راهنمایی می‌کند که کدام موتور را می‌توانیم نصب کنیم!                    |
| header  | این پارامتر، شماره سطری را نشان می‌دهد که اسم ستون‌ها در آن آمده است. توضیحات تکمیلی را می‌توانید از جدول‌های قبلی مطالعه کنید.                                                                                                                                                                                                                                                 |


</div>

In [8]:
caption = "Racial composition of the population of Minnesota"

df = pd.read_html('https://en.wikipedia.org/wiki/Minnesota', match=caption)[0]
df

ImportError: lxml not found, please install it

<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=3>
        <b>مثال تابع read_html</b>
        <br>
کد یک جدول به HTML در رشته source نوشته شده است. جدول را در دیتافریمی بارگذاری کنید و سطرهایی را از دیتافریم انتخاب کنید که ستون Age در آن‌ها کمترمساوی 24 باشد.
</div>

In [4]:
source = """
    <!DOCTYPE html>
<html>
<head>
</head>
<body>
<table>
  <tr>
    <th>Name</th>
    <th>Family</th>
    <th>Age</th>
  </tr>
  <tr>
    <td>Sajjad</td>
    <td>Yazdanparast</td>
    <td>23</td>
  </tr>
  <tr>
    <td>Parto</td>
    <td>Shahroodi</td>
    <td>25</td>
  </tr>
  <tr>
    <td>Hadi</td>
    <td>Sotude</td>
    <td>28</td>
  </tr>
  <tr>
    <td>Hamed</td>
    <td>Maansoury</td>
    <td>25</td>
  </tr>
  <tr>
    <td>SeyedParsa</td>
    <td>Mirtaheri</td>
    <td>24</td>
  </tr>
  <tr>
    <td>MohammadMahdi</td>
    <td>Shokri</td>
    <td>24</td>
  </tr>
  <tr>
    <td>MohammadBagher</td>
    <td>Tabrizi</td>
    <td>28</td>
  </tr>
</table>
</body>
</html>
"""

df = pd.read_html(source)[0]
df[df.Age <= 24]

            Name        Family  Age
0         Sajjad  Yazdanparast   23
4     SeyedParsa     Mirtaheri   24
5  MohammadMahdi        Shokri   24